# Meta Data for SEO

## Homepage
title = "Vachnamrut"
titleSeparator = "-"
titleAddition = "The holy Granth of Swaminarayan Bhagwan"
description = "Vachnamrut is the book wich contains Speech of Swaminarayan Bhagwan compiled by Nand santo."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "vanpariyar.in"
titleHome = "Vachnamrut"

## Twitter Cards
twitterSite = "@VanpariyaRonakJ"
twitterCreator = "@VanpariyaRonakJ"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Vachnamrut"
schemaAuthor = "Swaminarayan Bhagwan"
schemaAuthorTwitter = "https://twitter.com/VanpariyaRonakJ"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/ronak-vanpariya/"
schemaAuthorGitHub = "https://github.com/vanpariyar"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/VanpariyaRonakJ"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/vanpariyar/vachnamrut"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) since 2020"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/vanpariyar/vachnamrut"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
